/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calc_prog_1(char *host, int a, int b)
{
	CLIENT *clnt;
	int  *result_1;
	dato  suma_1_arg;
	int  *result_2;
	dato  resta_1_arg;
	int  *result_3;
	dato  multiplicacion_1_arg;
	float  *result_4;
	dato  division_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROG, CALC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	suma_1_arg.a = a;
	suma_1_arg.b = b;
	result_1 = suma_1(&suma_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("result = %d\n", *result_1);
	}

	resta_1_arg.a = a;
	resta_1_arg.b = b;
	result_2 = resta_1(&resta_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("result = %d\n", *result_2);
	}


	multiplicacion_1_arg.a = a;
	multiplicacion_1_arg.b = b;
	result_3 = multiplicacion_1(&multiplicacion_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("result = %d\n", *result_3);
	}


	division_1_arg.a = a;
	division_1_arg.b = b;
	result_4 = division_1(&division_1_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("result = %f\n", *result_4);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int a, b;
	if (argc !=4) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	if((a = atoi(argv[2])) == 0 && *argv[2] != '0'){
		fprintf(stderr, "invalid value: %s\n", argv[2]);
		exit(1);
	}
	if((b = atoi(argv[3])) == 0 && *argv[3] != '0'){
		fprintf(stderr, "invalid value: %s\n", argv[3]);
		exit(1);
	}
	calc_prog_1 (host, a, b);
exit (0);
}
